-- GenID Protocol: close the step-insert/finalize race, add finalize lock
-- ownership (Sept 18 second follow-up)
--
-- PROBLEM 1 — a step could be inserted after the session's root hash was
-- already computed. finalize's guard against a NEW finalize call starting
-- mid-step-write was solved (the 'finalizing' status lock), but nothing
-- stopped the REVERSE: a step request that read status = 'active', then
-- spent several seconds in an external generation call, then inserted its
-- row — even though finalize had, in the meantime, flipped the session to
-- 'finalizing' and already read/hashed the (now stale) step list. The step
-- route's status check and its INSERT were two separate round trips with an
-- unbounded gap between them.
--
-- Fix: create_step_if_session_active() does the "is this session still
-- active" check and the INSERT inside ONE transaction, with `select ... for
-- update` locking the session row first. A concurrent
-- `update genid_sessions set status = 'finalizing' where status = 'active'`
-- (tryBeginFinalizing) takes the same kind of row lock, so Postgres
-- serializes the two: whichever commits first wins, and the loser sees the
-- other's committed state before deciding anything — an insert can no
-- longer land after finalize has already moved past reading the step list.
create or replace function create_step_if_session_active(
  p_session_id uuid,
  p_step_number integer,
  p_step_type text,
  p_edit_type text,
  p_prompt_text text,
  p_model_used text,
  p_model_request_id text,
  p_request_timestamp timestamptz,
  p_response_timestamp timestamptz,
  p_output_storage_path text,
  p_output_hash text,
  p_prior_step_signature text,
  p_step_hash text,
  p_step_signature text,
  p_user_note text,
  p_auto_suggested_note text
) returns genid_steps
language plpgsql
as $$
declare
  v_status text;
  v_step genid_steps;
begin
  select status into v_status from genid_sessions where id = p_session_id for update;

  if v_status is null then
    raise exception 'SESSION_NOT_FOUND';
  end if;
  if v_status <> 'active' then
    raise exception 'SESSION_NOT_ACTIVE';
  end if;

  insert into genid_steps (
    session_id, step_number, step_type, edit_type, prompt_text, model_used,
    model_request_id, request_timestamp, response_timestamp,
    output_storage_path, output_hash, prior_step_signature, step_hash,
    step_signature, user_note, auto_suggested_note, is_final_selection
  ) values (
    p_session_id, p_step_number, p_step_type, p_edit_type, p_prompt_text, p_model_used,
    p_model_request_id, p_request_timestamp, p_response_timestamp,
    p_output_storage_path, p_output_hash, p_prior_step_signature, p_step_hash,
    p_step_signature, p_user_note, p_auto_suggested_note, false
  )
  returning * into v_step;

  return v_step;
end;
$$;

-- PROBLEM 2 — the 'finalizing' lock had no owner. tryReclaimStaleFinalizing
-- lets a second request take over when the first is presumed dead, but
-- nothing stopped the FIRST request — if it was merely slow, not actually
-- dead — from later calling abortFinalizing() or finalizeSession() and
-- silently clobbering the second request's in-progress or already-committed
-- work, since both of those only checked `status`, not who set it.
--
-- finalizing_lock_token is regenerated by every tryBeginFinalizing /
-- tryReclaimStaleFinalizing call and threaded through to abortFinalizing
-- and finalizeSession, which now both require a token match. A request
-- whose token has been superseded finds its release/commit calls affect
-- zero rows instead of touching a lock it no longer holds.
alter table genid_sessions
  add column if not exists finalizing_lock_token text;
